FROM ubuntu:latest

RUN apt-get update && apt-get install -y linux-headers-generic build-essential haskell-platform ghc ca-certificates libghc-postgresql-libpq-dev libghc-zlib-dev haskell-stack tar

RUN stack config set system-ghc --global true
