resolver: lts-6.8

packages:
- '.'
- location:
    git: 'git@github.com:diogob/pasta.git'
    commit: 'master'

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
